FROM node:24.19.0-alpine AS build
WORKDIR /workspace/FrontEnd

RUN corepack enable

COPY FrontEnd/package.json FrontEnd/pnpm-lock.yaml FrontEnd/pnpm-workspace.yaml FrontEnd/.npmrc ./
COPY FrontEnd/apps/member ./apps/member
COPY FrontEnd/packages/member-common ./packages/member-common
COPY FrontEnd/packages/api-contract ./packages/api-contract

RUN corepack pnpm install --filter member... --frozen-lockfile \
    && corepack pnpm --filter member build:prod

FROM nginx:1.27-alpine
COPY infra/nginx/web/member-web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/FrontEnd/apps/member/dist/ /usr/share/nginx/html/
